[package]
name = "memutil"
version = "0.1.0"
edition = "2024"

[dependencies]
bytemuck = "1.24"
clap = { version = "4.5", features = ["derive"] }
elf = "0.8"
glam = { version = "0.30", features = ["bytemuck"] }
libc = "0.2"
thiserror = "2.0"
